name: Upload to Qiniu

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Qiniu
        uses: luochongfei/up2qn@0.0.1
        with:
          bucket: ${{ secrets.QINIU_BUCKET }}
          zone: 东南亚       # 华东 / 华北 / 华南 / 北美 / 东南亚
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          local_dir: .     # 上传整个仓库
          local_exclude: |
            .git
            .github
          target_dir: /     # 上传到空间根目录
