name: 上传到七牛存储
on: push

jobs:
  job1:
    name: 上传到七牛云任务
    runs-on: Ubuntu-20.04
    environment: Production  # Make sure the environment is defined here
    steps:
      - name: 检索文件
        uses: actions/checkout@v2

      - name: 执行上传
        uses: luochongfei/up2qn@master
        with:
          bucket: cdn-zwx
          zone: 东南亚
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          local_dir: .
          local_exclude: ""
          target_dir: /
