name: Upload to Qiniu

on:
  push:
    branches:
      - main  # 监听 main 分支，如需其他分支可改

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to 
        uses: qiniu-action/qiniu-action@v1.3.0
        with:
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          bucket: ${{ secrets.QINIU_BUCKET }}
          zone: "东南亚"  # 配置七牛云区域（华东 / 华南 / 华北 / 东南亚 / 北美）
          local_dir: "."  # 上传整个仓库
          exclude: |
            .git
            .github
          target_dir: "/"  # 上传到七牛云的根目录
