name: Sync Cloudflare R2 to Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for R2
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.R2_ENDPOINT }}
          region = auto
          EOF

      - name: Sync R2 bucket to repo folder
        run: |
          mkdir -p r2-sync
          rclone sync r2:${{ secrets.R2_BUCKET_NAME }} r2-sync --progress --fast-list

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add r2-sync
          git diff --cached --quiet || \
            git commit -m "Sync R2 files to repository"
          git push origin HEAD:r2-sync
