name: Sync R2 to Branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: r2-sync
          fetch-depth: 0

      - name: Set up Python and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade awscli

      - name: Sync R2 files to branch
        run: |
          R2_BUCKET=${{ secrets.R2_BUCKET }}
          R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID=${{ secrets.R2_KEY }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET }}
          BRANCH=r2-sync

          mkdir -p r2-files

          echo "Downloading files from R2..."
          aws s3 sync s3://$R2_BUCKET ./r2-files \
            --endpoint-url https://$R2_ACCOUNT_ID.r2.cloudflarestorage.com

          echo "Switching to branch $BRANCH..."
          git checkout $BRANCH

          echo "Copying files to branch..."
          rsync -a --delete ./r2-files/ ./

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync R2 files" || echo "No changes to commit"
          git push origin $BRANCH
