name: Sync to R2
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changes
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changes.txt
          echo "Changed files:"
          cat changes.txt

      - name: Sync added/modified files to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET }}
        run: |
          while read status file; do
            [[ "$file" == ".github/workflows/"* ]] && continue
            if [[ "$status" == "A" || "$status" == "M" ]]; then
              echo "Uploading $file"
              aws s3 cp "$file" "s3://cdn/$file" \
                --endpoint-url https://3e074a499835faf39e26a69ca96198e9.r2.cloudflarestorage.com
            fi
          done < changes.txt

      - name: Delete removed files from R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET }}
        run: |
          while read status file; do
            [[ "$file" == ".github/workflows/"* ]] && continue
            if [[ "$status" == "D" ]]; then
              echo "Deleting $file"
              aws s3 rm "s3://cdn/$file" \
                --endpoint-url https://3e074a499835faf39e26a69ca96198e9.r2.cloudflarestorage.com
            fi
          done < changes.txt
