name: Sync R2 to Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout r2-sync branch
        uses: actions/checkout@v3
        with:
          ref: r2-sync
          fetch-depth: 0

      - name: Clean branch
        run: |
          git rm -rf . || true
          git clean -fdx

      - name: Sync files from R2
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_KEY }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET }} 
        run: | 
          while read status file; do [[ "$file" == ".github/workflows/"* ]] && continue if [[ "$status" == "A" || "$status" == "M" ]]; then echo "Uploading $file" 
          aws s3 cp "$file" "s3://cdn/$file" \ 
            --endpoint-url https://3e074a499835faf39e26a69ca96198e9.r2.cloudflarestorage.com

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Sync from R2" || echo "No changes to commit"
          git push origin r2-sync
