name: Sync R2 to r2-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync_r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout r2-sync branch
        uses: actions/checkout@v3
        with:
          ref: r2-sync
          fetch-depth: 0

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Clean branch
        run: |
          git rm -rf . || true
          git clean -fdx

      - name: Sync from R2
        run: |
          rclone copy Cloudflare:${{ cdn }} ./ \
            --transfers=8 --checkers=16 --exclude=.git/** --exclude=.github/** --exclude=README.md
        env:
          RCLONE_CONFIG_PASS: ''

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: sync from R2'
          add: './'
